# -- PostgreSQL config
config: |-
  max_wal_size = '4GB'
  shared_buffers = '2GB'

# -- [AidboxDB environment variables](https://docs.aidbox.app/reference/configuration/environment-variables/aidboxdb-environment-variables)
env:
  PGDATA: /data/pg
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres

storage:
  # -- Storage className to use
  className: ""
  # -- Storage volume size request
  size: 300Gi

image:
  repository: healthsamurai/aidboxdb
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  # Has one-to-one mapping to the PostgreSQL version.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# -- Additional volumes
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# -- Additional volume mounts
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true
