config:
  max_wal_size: 4GB
  shared_buffers: 2GB

env:
  PGUSER: postgres
  PGPASSWORD: postgres

storageClassName: ""
storageSize: 300Gi


image:
  repository: healthsamurai/aidboxdb
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
