apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aidboxdb.fullname" . }}-data
  labels:
    {{- include "aidboxdb.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ required "missing storage.size value" .Values.storage.size }}
  {{- if .Values.storage.className }}
  storageClassName: {{ .Values.storage.className }}
  {{- end }}
