apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aidbox.fullname" . }}
  labels:
    {{- include "aidbox.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  AIDBOX_BASE_URL: {{ .Values.protocol }}://{{ .Values.host }}
  PGHOST: {{ required "missing config PGHOST value" .Values.config.PGHOST | quote }}
