apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aidbox.fullname" . }}
  labels:
    {{- include "aidbox.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  AIDBOX_ADMIN_ID: {{ required "missing AIDBOX_ADMIN_ID value" .AIDBOX_ADMIN_ID | b64enc }}
  AIDBOX_ADMIN_PASSWORD: {{ required "missing AIDBOX_ADMIN_PASSWORD value" .AIDBOX_ADMIN_PASSWORD | b64enc }}
  AIDBOX_CLIENT_ID: {{ required "missing AIDBOX_CLIENT_ID value" .AIDBOX_CLIENT_ID | b64enc }}
  AIDBOX_CLIENT_SECRET: {{ required "missing AIDBOX_CLIENT_SECRET value" .AIDBOX_CLIENT_SECRET | b64enc }}
  AIDBOX_LICENSE: {{ required "missing AIDBOX_LICENSE value" .AIDBOX_LICENSE | b64enc }}
  PGUSER: {{ required "missing PGUSER value" .PGUSER | b64enc }}
  PGPASSWORD: {{ required "missing PGPASSWORD value" .PGPASSWORD | b64enc }}
  {{- end }}
