apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aidbox.fullname" . }}
  labels:
    {{- include "aidbox.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  AIDBOX_ADMIN_ID: {{ .AIDBOX_ADMIN_ID | b64enc }}
  AIDBOX_ADMIN_PASSWORD: {{ .AIDBOX_ADMIN_PASSWORD | b64enc }}
  AIDBOX_CLIENT_ID: {{ .AIDBOX_CLIENT_ID | b64enc }}
  AIDBOX_CLIENT_SECRET: {{ .AIDBOX_CLIENT_SECRET | b64enc }}
  {{ if .AIDBOX_CLUSTER_SECRET }}AIDBOX_CLUSTER_SECRET: {{ .AIDBOX_CLUSTER_SECRET | b64enc }}{{ end }}
  {{ if .AIDBOX_SUPERUSER }}AIDBOX_SUPERUSER: {{ .AIDBOX_SUPERUSER | b64enc }}{{ end }}
  {{ if .AIDBOX_ES_AUTH }}AIDBOX_ES_AUTH: {{ .AIDBOX_ES_AUTH | b64enc }}{{ end }}
  AIDBOX_LICENSE: {{ .AIDBOX_LICENSE | b64enc }}
  PGUSER: {{ .PGUSER | b64enc }}
  PGPASSWORD: {{ .PGPASSWORD | b64enc }}
  {{- end }}
