apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aidbox.fullname" . }}
  labels:
    {{- include "aidbox.labels" . | nindent 4 }}
data:
  {{- with .Values.config }}
  AIDBOX_ADMIN_ID: {{ required "AIDBOX_ADMIN_ID is required" .AIDBOX_ADMIN_ID | b64enc }}
  AIDBOX_ADMIN_PASSWORD: {{ required "AIDBOX_ADMIN_PASSWORD is required" .AIDBOX_ADMIN_PASSWORD | b64enc }}
  AIDBOX_CLIENT_ID: {{ required "AIDBOX_CLIENT_ID is required" .AIDBOX_CLIENT_ID | b64enc }}
  AIDBOX_CLIENT_SECRET: {{ required "AIDBOX_CLIENT_SECRET is required" .AIDBOX_CLIENT_SECRET | b64enc }}
  {{ if .AIDBOX_CLUSTER_SECRET }}AIDBOX_CLUSTER_SECRET: {{ .AIDBOX_CLUSTER_SECRET | b64enc }}{{ end }}
  {{ if .AIDBOX_SUPERUSER }}AIDBOX_SUPERUSER: {{ .AIDBOX_SUPERUSER | b64enc }}{{ end }}
  {{ if .AIDBOX_ES_AUTH }}AIDBOX_ES_AUTH: {{ .AIDBOX_ES_AUTH | b64enc }}{{ end }}
  AIDBOX_LICENSE: {{ required "AIDBOX_LICENSE is required" .AIDBOX_LICENSE | b64enc }}
  PGUSER: {{ required "PGUSER is required" .PGUSER | b64enc }}
  PGPASSWORD: {{ required "PGPASSWORD is required" .PGPASSWORD | b64enc }}
  {{- end }}
