apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aidbox.fullname" . }}
  labels:
    {{- include "aidbox.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ required (printf "missing secret %s value" $key) $val | b64enc }}
  {{- end }}

  {{- with .Values.secrets }}
  {{- if not .AIDBOX_LICENSE }}
  AIDBOX_LICENSE_ID: {{ required "missing secret AIDBOX_LICENSE or AIDBOX_LICENSE_ID value" .AIDBOX_LICENSE_ID | b64enc }}
  AIDBOX_LICENSE_KEY: {{ required "missing secret AIDBOX_LICENSE or AIDBOX_LICENSE_KEY value" .AIDBOX_LICENSE_KEY | b64enc }}
  {{- end }}
  {{- end }}
